### ISSUE TITLE
Unable to start receiver in background

### ISSUE THREAD

**Issue by hckwlf** [gopalanrc/cryptocurrency-alert#1]
```
FATAL EXCEPTION: main Process: com.namit.cryptocurrencyalert, PID: 6350
java.lang.RuntimeException: Unable to start receiver com.namit.cryptocurrencyalert.service.AlarmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.namit.cryptocurrencyalert/.service.CurrencyPriceCheckService (has extras) }: app is in background uid UidRecord{47192b6 u0a81 RCVR idle procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
at android.app.ActivityThread.-wrap17(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6540)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.namit.cryptocurrencyalert/.service.CurrencyPriceCheckService (has extras) }: app is in background uid UidRecord{47192b6 u0a81 RCVR idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1497)
at android.app.ContextImpl.startService(ContextImpl.java:1453)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at com.namit.cryptocurrencyalert.service.AlarmReceiver.onReceive(AlarmReceiver.java:18)
```

**Comment by gopalanrc** [comment]
Fixed.
