### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by hckwlf** [gopalanrc/cryptocurrency-alert#2]
`FATAL EXCEPTION: IntentService[CurrencyPriceCheckService]
                                                                             Process: com.namit.cryptocurrencyalert, PID: 6932
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.namit.cryptocurrencyalert.model.CryptocurrencyAlert.getFromSymbol()' on a null object reference
                                                                                 at com.namit.cryptocurrencyalert.service.CurrencyPriceCheckService.onHandleIntent(CurrencyPriceCheckService.java:45)
                                                                                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by gopalanrc** [comment]
Fixed.
